[project]
name = "files-to-prompt-v2"
version = "0.1"
description = "Concatenate a directory full of files into a single prompt for use with LLMs"
requires-python = ">=3.8"
authors = [{name = "Ahmad M. Osman"}, {name = "Simon Willison"}]
license = {text = "Apache-2.0"}
classifiers = [
    "License :: OSI Approved :: Apache Software License"
]
keywords = [
    "prompt", "llm", "concatenate", "files", "directory", "ai", "artificial intelligence", "language model", "claude", "xml", "cli", "command line", "ignore", "hidden files", "file processing", "text processing"
]
dependencies = [
    "click"
]
readme = "README.md"

[project.urls]
Homepage = "https://github.com/TheAhmadOsman/files-to-prompt"
Changelog = "https://github.com/TheAhmadOsman/files-to-prompt/releases"
Issues = "https://github.com/TheAhmadOsman/files-to-prompt/issues"
CI = "https://github.com/TheAhmadOsman/files-to-prompt/actions"

[tool.uv]
default-groups = []

[dependency-groups]
test = [
    "pytest",
]

[project.scripts]
files-to-prompt = "files_to_prompt.cli:cli"
